apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: postgres-${n}
  name: postgres-${n}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-${n}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-${n}
    spec:
      containers:
        - name: postgres
          image: postgres:11
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: postgresql
              name: blob-valid-data-pvc-${n}
      restartPolicy: Always
      volumes:
        - name: blob-valid-data-pvc-${n}
          persistentVolumeClaim:
            claimName: blob-valid-data-pvc-${n}
