
- route53:
    state: get
    zone: {{ domain }}
    record: "{{ cluster }}.{{ domain }}"
    type: A
  register: rec
- name: list the zone records
  debug: 
    var: rec
- route53:
    state: present
    zone: {{ domain }}
    record: "{{ cluster }}.{{ domain }}"
    type: A
    ttl: 7200
    value: {{ public_ip }}
    wait: yes
  when: "{{ cluster }}.{{ domain }}" not in "{{ rec.set.ttl }}"    
