---
# tasks file for dns_update
- debug:
    msg: Public dns is {{ cluster }}.{{ domain }} and the A record is {{ public_ip }}
#- name: Fetching the DNS zone records
#  route53:
#    state: get
#    zone: "{{ domain }}"
#    record: "{{ cluster }}.{{ domain }}"
#    type: A
#  register: rec
#- name: list the zone records
#  debug:
#    msg: "{{ rec.set.record }}"
- route53:
    state: present
    zone: "{{ domain }}"
    record: "{{ cluster }}.{{ domain }}"
    type: A
    ttl: 7200
    value: "{{ public_ip }}"
    wait: yes
#  when: {{ cluster }}.{{ domain }} not in {{ rec.set.record }}
