apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nfs-nfs-server-provisioner-0
  labels:
    tier: prod
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: "data-nfs-server-provisioner"
  storageClassName: manual
