- hosts: all
  become: yes
  tasks:
  #  - name: install Docker
  #    apt:
  #      name: docker.io
  #      state: present
  #      update_cache: true

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl

  # - name: Configure node ip
  #   lineinfile:
  #     path: /etc/default/kubelet
  #     line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: enable iscsid service
    service:
      name: iscsi
      enabled: yes

  - name: start iscsid service
    service:
      name: iscsi
      state: started

# - hosts: master
#   become: yes
#   tasks:
#    - name: install kubectl
#      apt:
#        name: kubectl=1.16.0-00
#        state: present
#        force: yes
