- hosts: master
  become: yes
  tasks:
    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: |
        swapoff -a

    - name: initialize the cluster
      become_user: root
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors DirAvailable--var-lib-etcd >> cluster_initialized.txt
      args:
        chdir: $HOME
        # creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: install Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        # creates: pod_network_setup.txt

    - name: Install open ebs for volume management
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://openebs.github.io/charts/openebs-operator-1.7.0.yaml >> volume_storage_setup.txt
      args:
        chdir: $HOME
        # creates: volume_storage_setup.txt