apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: cassandra-init-01
    tier: prod
  name: cassandra-init-01
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: instance
                operator: In
                values:
                - node-1
            weight: 100
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: instance
                  operator: In
                  values:
                  - node-1
              topologyKey: kubernetes.io/hostname
            weight: 100
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: instance
                  operator: In
                  values:
                  - node-none
                  - node-none
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - bash
        - /0chain/bin/cassandra-init.sh
        env:
        - name: CASSANDRA_HOST
          value: cassandra-01
        image: cassandra:latest
        name: cassandra-init-01
        resources:
          limits:
            cpu: 400m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
        - mountPath: /0chain/bin
          name: sharder-bin-volume
        - mountPath: /0chain/sql/txn_summary.sql
          name: sharder-sql-volume
          subPath: txn_summary.sql
        - mountPath: /0chain/sql/zerochain_keyspace.sql
          name: sharder-sql-volume
          subPath: zerochain_keyspace.sql
        - mountPath: /0chain/sql/magic_block_map.sql
          name: sharder-sql-volume
          subPath: magic_block_map.sql
      imagePullSecrets:
      - name: regcred
      restartPolicy: Never
      volumes:
      - configMap:
          items:
          - key: truncate_tables.sql
            path: truncate_tables.sql
          - key: txn_summary.sql
            path: txn_summary.sql
          - key: zerochain_keyspace.sql
            path: zerochain_keyspace.sql
          - key: magic_block_map.sql
            path: magic_block_map.sql
          name: sharder-sql
        name: sharder-sql-volume
      - configMap:
          defaultMode: 493
          items:
          - key: cassandra-init.sh
            path: cassandra-init.sh
          - key: scylla-init.sh
            path: scylla-init.sh
          - key: wait-for-service.sh
            path: wait-for-service.sh
          name: sharder-bin
        name: sharder-bin-volume
