apiVersion: v1
kind: Service
metadata:
  labels:
    app: sharder-01
    tier: prod
  name: "sharder-01"
spec:
  ports:
  - name: "sharder-01"
    port: 31101
    targetPort: 31101
  type: NodePort
  selector:
    app: sharder-01
    tier: prod
