apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharder-data-pvc-01
  labels:
    tier: prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath
