apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharder-log-pvc-01
  labels:
    tier: prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
