  apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: 0chain-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
    rules:
    - host: one.devnet-0chain.net
      http:
        paths:
        - backend:
            serviceName: explorer
            servicePort: 80
          path: /
        - backend:
            serviceName: recorder
            servicePort: 80
          path: /recorder(/|$)(.*)
        - backend:
            serviceName: worker
            servicePort: 80
          path: /dns(/|$)(.*)
        - backend:
            serviceName: zproxy
            servicePort: 31082
          path: /proxy(/|$)(.*)