apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sharder-${n}
    tier: prod
  name: sharder-${n}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharder-${n}
      tier: prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sharder-${n}
        tier: prod
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - cassandra-${n}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: sharder-${n}
          image: 0chainkube/sharder:${TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 312${n}
          resources:
            limits:
              cpu: 500m
              memory: 1.5Gi
            requests:
              cpu: 100m
              memory: 500Mi
          command:
            - /bin/sh
            - -c
            - mkdir -p /0chain/data/blocks && mkdir -p /0chain/data/rocksdb && ./bin/sharder --deployment_mode 0 --keys_file config/b0snode${n}_keys.txt --minio_file config/minio_config.txt
          env:
            - name: CASSANDRA_CLUSTER
              value: cassandra-${n}
            - name: DOCKER
              value: "true"
          volumeMounts:
            - mountPath: /0chain/config/magicBlock.json
              name: magic-block-config
              subPath: magicBlock.json
            - mountPath: /0chain/config
              name: sm-config-pvc
            - mountPath: /0chain/config/n2n_delay.yaml
              name: n2n-delay-yaml
              subPath: n2n_delay.yaml
            - mountPath: /0chain/config/sc.yaml
              name: sc-config
              subPath: sc.yaml
            - mountPath: /0chain/config/minio_config.txt
              name: minio-config-sharder
              subPath: minio_config.txt
            - mountPath: /0chain/config/b0owner_keys.txt
              name: owner-keys-config
              subPath: b0owner_keys.txt  
            - mountPath: /0chain/config/0chain.yaml
              name: zchain-yaml-config
              subPath: 0chain.yaml
            - mountPath: /0chain/config/cassandra
              name: sharder-cassandra-config
            - mountPath: /0chain/log
              name: sharder-log-pvc-${n}
            - mountPath: /0chain/data
              name: sharder-data-pvc-${n}
        - name: filebeat-sidecar
          image: docker.elastic.co/beats/filebeat:7.8.0
          volumeMounts:
          - name: sharder-log-pvc-${n}
            mountPath: /0chain/log
          - name: filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat.yml
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: magic-block-config
          configMap:
            name: magic-block-config
            defaultMode: 0755 
        - name: n2n-delay-yaml
          configMap:
            name: n2n-delay-yaml
            defaultMode: 0755
        - name: sc-config
          configMap:
            name: sc-config
            defaultMode: 0755
        - name: minio-config-sharder
          secret:
            secretName: minio-config-sharder
            defaultMode: 0755
        - name: owner-keys-config
          configMap:
            name: owner-keys-config
            defaultMode: 0755 
        - name: zchain-yaml-config
          configMap:
            name: zchain-yaml-config
            defaultMode: 0755
        - name: sharder-cassandra-config
          configMap:
            name: sharder-cassandra-config
            defaultMode: 0755
        - name: sharder-log-pvc-${n}
          persistentVolumeClaim:
            claimName: sharder-log-pvc-${n}
        - name: sharder-data-pvc-${n}
          persistentVolumeClaim:
            claimName: sharder-data-pvc-${n}
        - name: sm-config-pvc
          persistentVolumeClaim:
            claimName: sm-config-pvc
        - name: filebeat-config
          configMap:
            name: filebeat-config
            defaultMode: 0755
