apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 0proxy-data-pvc
  labels:
    tier: prod
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ${rwm_sc}