apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blob-tmp-pvc-${n}
  labels:
    tier: prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ${fs_type}