apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valid-files-pvc-${n}
  labels:
    tier: prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ${fs_type}
