apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: mongo-init
  name: mongo-init
spec:
  backoffLimit: 15
  template:
    spec:
      containers:
        - name: mongo-init
          image: mongo
          args: 
            - bash
            - -c
            - "sleep 180; mongo  'mongodb://mongo-0.mongo:27017' --eval 'rs.initiate({_id : \"rs0\", members: [ { _id: 0, host: \"mongo-0.mongo:27017\" }, { _id: 1, host: \"mongo-1.mongo:27017\" }, { _id: 2, host: \"mongo-2.mongo:27017\" } ] })'"
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: regcred
# rs.initiate({_id : "rs0", members: [ { _id: 0, host: "mongo-0.mongo:27017" }, { _id: 1, host: "mongo-1.mongo:27017" }, { _id: 2, host: "mongo-2.mongo:27017" } ] })        