apiVersion: v1
kind: Service
metadata:
  labels:
    app: sharder-${n}
    tier: prod
  name: "sharder-${n}"
spec:
  ports:
  - name: "sharder-${n}"
    port: 311${n}
    targetPort: 311${n}
  type: NodePort
  selector:
    app: sharder-${n}
    tier: prod
