apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: 0box
    tier: prod
  name: 0box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 0box
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: 0box
        tier: prod
    spec:
      containers:
        - image: 0chaintest/0box:latest
          imagePullPolicy: Always
          name: 0box
          args:
          - ./bin/zbox 
          - --deployment_mode 
          - "0" 
          - --keys_file 
          - config/0box_keys_bls.txt 
          - --nodes_file 
          - nodes
          env:
          - name: DOCKER
            value: 'true'
          - name: DB_NAME
            value: zbox
          - name: DB_USER
            value: zbox_user
          - name: DB_PASSWORD
            value: zbox_server
          - name: DB_HOST
            value: postgres-zbox
          - name: DB_PORT
            value: "5432"
          ports:
          - containerPort: 31081
          volumeMounts:
          - mountPath: /0box/static
            name: 0box-static-pvc
          - mountPath: /0box/config/0box.yaml
            name: 0box-config
            subPath: 0box.yaml
          - mountPath: /0box/config/nodes.yaml
            name: nodes-yaml-pvc
            subPath: nodes.yaml
          - mountPath: /0box/config/apple-url-association.json
            name: 0box-apple-url-config
            subPath: apple-url-association.json
          - mountPath: /0box/config/0box_firebase_key.json
            name: 0box-firebase-config
            subPath: 0box_firebase_key.json
          - mountPath: /0box/config/0box_keys_bls.txt
            name: zbox-config-pvc
            subPath: 0box_keys_bls.txt 
          - mountPath: /0box/data
            name: 0box-data-pvc
          - mountPath: /0box/certs
            name: 0box-certs-pvc
          - mountPath: /0box/log
            name: 0box-log-pvc
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: nodes-yaml-pvc
        persistentVolumeClaim:
          claimName: nodes-yaml-pvc
      - name: 0box-static-pvc
        persistentVolumeClaim:
          claimName: 0box-static-pvc
      - name: 0box-config  
        configMap:
          name: 0box-config
          defaultMode: 0755
      - name: 0box-apple-url-config  
        configMap:
          name: 0box-apple-url-config
          defaultMode: 0755
      - name: zbox-config-pvc
        persistentVolumeClaim:
          claimName: zbox-config-pvc
      - name: 0box-firebase-config  
        configMap:
          name: 0box-firebase-config           
          defaultMode: 0755
      - name: 0box-data-pvc
        persistentVolumeClaim:
          claimName: 0box-data-pvc
      - name: 0box-log-pvc
        persistentVolumeClaim:
          claimName: 0box-log-pvc
      - name: 0box-certs-pvc
        persistentVolumeClaim:
          claimName: 0box-certs-pvc
