apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miner-data-pvc-${n}
  labels:
    tier: prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: ${data_volume_size}Gi
  storageClassName: ${fs_type}
