apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 0box-static-pvc
  labels:
    tier: prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ${fs_type}