apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 0box-data-pvc
  labels:
    tier: prod
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs