apiVersion: v1
kind: Service
metadata:
  labels:
    app: worker
    tier: prod
  name: worker
spec:
  ports:
  - name: "worker"
    port: 80
    targetPort: 9091
  type: NodePort
  selector:
    app : worker
    tier: prod