all:
  hosts:
    node1:
      ip: 38.32.112.211
      access_ip: 38.32.112.211
      ansible_host: 38.32.112.211
    node2:
      ip: 38.32.112.212
      ansible_host: 38.32.112.212
      access_ip: 38.32.112.212
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-node:
        kube-master:
    calico-rr:
      hosts: {}
