all:
  hosts:
    node1:
      access_ip: 3.133.124.172
      ansible_host: 3.133.124.172
      ip: 172.31.15.146
    node2:
      ip: 172.31.6.247
      access_ip: 18.188.45.172
      ansible_host: 18.188.45.172
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
