apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  explorer
spec:
  prefix: /
  service: explorer
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  recorder
spec:
  prefix: /recorder
  service: recorder
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  worker
spec:
  prefix: /dns/
  service: worker
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  0proxy
spec:
  prefix: /proxy/
  service: zproxy:31082