apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-config-pvc
  labels:
    tier: prod
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: ${rwm_sc}