apiVersion: v1
kind: ConfigMap
metadata:
 name: filebeat-config
 namespace: test
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /0chain/log/0chain.log
    output:
      elasticsearch:
        hosts: ["http://elastic-cluster-es-http.elastic-system.svc.cluster.local:9200"]
        username: "elastic"
        password: "D0mx3N525SToPd8u71OA3N9w"