apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-zbox
    tier: prod
  name: postgres-zbox
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: postgres-zbox

